### ISSUE TITLE
Remove Default Template Config

### ISSUE THREAD

**Issue by ColonelPanicks** [openflighthpc/flight-inventory#143]
In `etc/templates.yaml` we have the following:
```
default:
  default: server.md.erb
data:
  default: asset.yml.erb
markdown:
  default: server.md.erb
  server: server.md.erb
  switch: switch.md.erb
flightcenter:
  default: serverFC.md.erb
  server: serverFC.md.erb
  switch: switchFC.md.erb
```

As I understand it, `inventory show` will use the `default` map. This seems a little redundant to me. Could we not default to say, `data` or `markdown`? (markdown being my default preference). 

The issue is that now the `default` template list will need to be maintained for different assets types, instead of the just the different outputs. (This was somewhat touched upon in #117 ).
